# Generated by Django 3.2.3 on 2024-01-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='steps',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
