# Generated by Django 3.2.23 on 2023-11-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_submit_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='excerpt',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='submit_form',
            old_name='excerpt',
            new_name='description',
        ),
        migrations.AddField(
            model_name='submit_form',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submit_form',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
