# Generated by Django 3.2.3 on 2024-01-11 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_post_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='steps',
        ),
    ]
